version: "3"
services:
  redis:
    image: redis:6.2-alpine
    command: /bin/sh -c "redis-server --port 6000"
    container_name: redis
    restart: unless-stopped
  web_app:
    container_name: sleepwalker_backend
    command: /bin/sh -c "/sleepwalker/scripts/entrypoint.sh"
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ${DB_PATH}:/sleepwalker/database
      - ${LOGS_PATH}:/sleepwalker/logs
    env_file:
      - .env
